### ISSUE TITLE
1/5號乙班

### ISSUE THREAD

**Issue by 40323217** [kmollee/2014_fall_cp#2]
學長明天我們班有要去上課唷!! 
還有就是 第15周跟2014 CP final project兩個專案都要做嗎,還是做期末報告(2014 CP final project)就好

**Comment by mdeta** [comment]
參照 pygroup 內容, 基本上以 final project 為主, 其餘內容可能以每週進度做個總結

**Comment by 40323217** [comment]
學長下星期一可以不要去上課嗎,有同學在問,還是有問題的可以去?

**Comment by kmollee** [comment]
可以, 同學們自行決定是否要來

**Comment by 40323217** [comment]
學長我想請問一下,假如前幾周(六、七周)的九九乘法表跟學號的openshift刪掉了,有需要重用嗎,老師是否會回去看? 還是他只有看期中考後的?

**Comment by kmollee** [comment]
九九乘法表似乎是期中之後的, 以期中考後為主
