### ISSUE TITLE
durpal 7 問題

### ISSUE THREAD

**Issue by kmolLin** [kmollee/2014_fall_cp#4]
在openshift上，原本用近端可以用資料夾方式管理我的模組，但是在openshift上他的sqL的絕對位置我應該去哪邊找到相關的資料，還是可以用什麼方法找到後端的資料，今天聽老師說似乎在他的database中可以找到，但是根本不知道要怎麼做連接。有方法嗎???

**Comment by kmollee** [comment]
check this [PHP MySQL 5.5 db connection in Openshift](http://stackoverflow.com/questions/22045035/php-mysql-5-5-db-connection-in-openshift)
